--FINANCE INFO ABOUT CLUB
SELECT
	C.NAME,
	C.CITY,
	C.BUDGET,
	COUNT(CT.ID),
	SUM(CT.WEEKLY_SALARY)
FROM CLUBS C
JOIN CONTRACTS CT ON C.ID = CT.CLUB_ID
WHERE C.NAME = 'MANCHESTER CITY'
GROUP BY C.ID, C.NAME, C.CITY, C.BUDGET;

--THE TOP HIGHEST PAID PLAYERS OF A PARTICULAR AGENT

SELECT
	P.FULL_NAME,
	P.POSITION,
	P.NATIONALITY,
	CT.WEEKLY_SALARY,
	CT.START_DATE,
	CT.END_DATE
FROM AGENTS A
JOIN PLAYERS P ON A.ID = P.AGENT_ID
JOIN CONTRACTS CT ON P.ID = CT.PLAYER_ID
WHERE A.FULL_NAME = 'Jorge Mendes'
ORDER BY CT.WEEKLY_SALARY DESC
LIMIT 5;

-- SEARCH FOR FREE AGENTS

SELECT DISTINCT
	A.FULL_NAME AS AGENT_NAME,
    A.RATING,
    P.FULL_NAME AS PLAYER_NAME,
    P.POSITION,
    C.NAME AS CURRENT_CLUB,
    CT.WEEKLY_SALARY
FROM AGENTS A
JOIN PLAYERS P ON A.ID = P.AGENT_ID
JOIN CONTRACTS CT ON P.ID = CT.PLAYER_ID
JOIN CLUBS C ON CT.CLUB_ID = C.ID
WHERE C.BUDGET >= 100000000
  AND A.RATING >= 8.00
  AND P.POSITION = 'FORWARD'
ORDER BY A.RATING DESC;